"""유튜브 플레이리스트 스타일 프리셋."""

GENRE_PRESETS = [
    # ── 재즈 ──
    {
        "id": "deep_bass_jazz",
        "category": "재즈",
        "name": "딥베이스 재즈",
        "emoji": "🎷",
        "tags": "재즈,딥베이스,야간",
        "description": "깊은 더블베이스가 살아있는 스무스 재즈",
        "genre": "Deep Jazz, Smooth Jazz",
        "mood": "고급스러운, 깊은, 늦은 밤",
        "tempo_bpm": 78,
        "vocal_style": "인스트루멘탈, 가끔 재즈 보컬",
        "instruments": "업라이트 베이스(전면), 색소폰, 피아노, 브러시 드럼",
        "production_style": "warm, deep sub bass, vinyl crackle, intimate club",
        "reference_artists": "Miles Davis, Chet Baker, Norah Jones",
    },
    {
        "id": "smooth_jazz",
        "category": "재즈",
        "name": "스무스 재즈",
        "emoji": "🥂",
        "tags": "재즈,스무스,라운지",
        "description": "와인바·라운지에서 듣는 부드러운 재즈",
        "genre": "Smooth Jazz, Lounge Jazz",
        "mood": "우아한, 편안한, 세련된",
        "tempo_bpm": 85,
        "vocal_style": "부드러운 재즈 보컬, 인스트루멘탈",
        "instruments": "색소폰, 일렉 피아노, 베이스, 라이트 드럼",
        "production_style": "polished, silky, lounge atmosphere",
        "reference_artists": "Sade, George Benson, Kenny G",
    },
    {
        "id": "coffee_jazz",
        "category": "재즈",
        "name": "커피 재즈",
        "emoji": "☕",
        "tags": "재즈,카페,아침",
        "description": "아침 커피와 함께 듣는 따뜻한 재즈",
        "genre": "Jazz, Bossa Nova",
        "mood": "따뜻한, 여유로운, 밝은",
        "tempo_bpm": 95,
        "vocal_style": "인스트루멘탈, 보사노바 보컬",
        "instruments": "어쿠스틱 기타, 피아노, 콘트라베이스, 브러시",
        "production_style": "acoustic, warm morning light, cozy cafe",
        "reference_artists": "Stan Getz, João Gilberto",
    },
    {
        "id": "bossa_nova",
        "category": "재즈",
        "name": "보사노바",
        "emoji": "🌴",
        "tags": "재즈,보사노바,브라질",
        "description": "브라질 리듬의 감성적인 보사노바",
        "genre": "Bossa Nova, Latin Jazz",
        "mood": "로맨틱, 여유로운, 열대",
        "tempo_bpm": 110,
        "vocal_style": "부드러운 남성/여성 보컬",
        "instruments": "나일론 기타, 피아노, 퍼커션, 베이스",
        "production_style": "gentle swing, nylon strings, beach sunset",
        "reference_artists": "Antônio Carlos Jobim, Astrud Gilberto",
    },
    {
        "id": "late_night_jazz",
        "category": "재즈",
        "name": "심야 재즈",
        "emoji": "🌃",
        "tags": "재즈,심야,스모키",
        "description": "새벽 2시 재즈바 분위기",
        "genre": "Cool Jazz, Bebop",
        "mood": "스모키, 고독한, 깊은",
        "tempo_bpm": 70,
        "vocal_style": "허스키 재즈 보컬, 인스트루멘탈",
        "instruments": "트럼펫, 색소폰, 피아노, 업라이트 베이스",
        "production_style": "dim lighting, smoky room, slow burn",
        "reference_artists": "Billie Holiday, John Coltrane",
    },
    {
        "id": "jazz_fusion",
        "category": "재즈",
        "name": "재즈 퓨전",
        "emoji": "⚡",
        "tags": "재즈,퓨전,일렉",
        "description": "록·펑크와 섞인 일렉트릭 재즈",
        "genre": "Jazz Fusion, Jazz Rock",
        "mood": "역동적, 복잡한, 에너지틱",
        "tempo_bpm": 120,
        "vocal_style": "인스트루멘탈",
        "instruments": "일렉 기타, 키보드, 베이스, 퓨전 드럼",
        "production_style": "technical, virtuosic, 70s fusion",
        "reference_artists": "Weather Report, Herbie Hancock",
    },
    # ── 칠/로파이 ──
    {
        "id": "lofi",
        "category": "칠/로파이",
        "name": "Lo-fi Hip Hop",
        "emoji": "📻",
        "tags": "Lo-fi,공부,휴식",
        "description": "공부·작업용 로파이 힙합 비트",
        "genre": "Lo-fi Hip Hop",
        "mood": "차분한, 향수적, 편안한",
        "tempo_bpm": 85,
        "vocal_style": "인스트루멘탈",
        "instruments": "로파이 피아노, 재즈 샘플, 비닐 크랙, 808",
        "production_style": "lo-fi, tape saturation, dusty drums",
        "reference_artists": "Nujabes, J Dilla, ChilledCow",
    },
    {
        "id": "chillhop",
        "category": "칠/로파이",
        "name": "칠합 (Chillhop)",
        "emoji": "🍃",
        "tags": "칠합,힙합,릴랙스",
        "description": "재즈 샘플이 섞인 칠한 힙합",
        "genre": "Chillhop, Jazz Hop",
        "mood": "느긋한, 그루브, 편안한",
        "tempo_bpm": 90,
        "vocal_style": "인스트루멘탈, 가끔 랩",
        "instruments": "재즈 샘플, 비트, 베이스, 로즈",
        "production_style": "chill beats, jazzy samples, mellow",
        "reference_artists": "Chillhop Music, Idealism",
    },
    {
        "id": "study_beats",
        "category": "칠/로파이",
        "name": "공부할 때 듣는 음악",
        "emoji": "📚",
        "tags": "공부,집중,배경",
        "description": "집중력을 높이는 배경 비트",
        "genre": "Ambient, Lo-fi",
        "mood": "집중, 차분한, 몰입",
        "tempo_bpm": 80,
        "vocal_style": "인스트루멘탈",
        "instruments": "피아노, 패드, 미니멀 비트",
        "production_style": "non-distracting, steady, focus-friendly",
        "reference_artists": "Lofi Girl, StudyMD",
    },
    {
        "id": "sleep_music",
        "category": "칠/로파이",
        "name": "수면 음악",
        "emoji": "😴",
        "tags": "수면,힐링,명상",
        "description": "잠들기 좋은 잔잔한 음악",
        "genre": "Ambient, New Age",
        "mood": "평화로운, 몽환적, 안정",
        "tempo_bpm": 55,
        "vocal_style": "인스트루멘탈, 워십",
        "instruments": "패드 신스, 피아노, 자연 소리",
        "production_style": "ultra soft, slow, no sudden changes",
        "reference_artists": "Max Richter, Brian Eno",
    },
    {
        "id": "cafe",
        "category": "칠/로파이",
        "name": "카페 음악",
        "emoji": "🏠",
        "tags": "카페,잔잔,어쿠스틱",
        "description": "카페 BGM 스타일의 편안한 음악",
        "genre": "Acoustic Pop, Indie Folk",
        "mood": "따뜻한, 편안한, 일상",
        "tempo_bpm": 92,
        "vocal_style": "부드러운 보컬, 인스트루멘탈",
        "instruments": "어쿠스틱 기타, 피아노, 가벼운 드럼",
        "production_style": "warm, background-friendly, gentle",
        "reference_artists": "Iron & Wine, José González",
    },
    {
        "id": "rainy",
        "category": "칠/로파이",
        "name": "비 오는 날",
        "emoji": "🌧️",
        "tags": "비,감성,몽환",
        "description": "비 오는 날 창밖을 보며 듣는 음악",
        "genre": "Indie, Ambient Pop",
        "mood": "우울한, 몽환적, 향수적",
        "tempo_bpm": 78,
        "vocal_style": "속삭이는 보컬, 허스키",
        "instruments": "로파이 피아노, 레인 샘플, 패드",
        "production_style": "reverb-heavy, melancholic, rain ambience",
        "reference_artists": "Bon Iver, Radiohead",
    },
    # ── 일렉트로닉 ──
    {
        "id": "deep_house",
        "category": "일렉트로닉",
        "name": "딥 하우스",
        "emoji": "🌊",
        "tags": "하우스,딥,클럽",
        "description": "깊고 그루비한 딥 하우스",
        "genre": "Deep House",
        "mood": "몽환적, 그루브, 세련된",
        "tempo_bpm": 122,
        "vocal_style": "소울풀 여성 보컬, 보컬 샘플",
        "instruments": "딥 베이스, 하우스 킥, 패드, 플루트",
        "production_style": "deep, groovy, warehouse vibe",
        "reference_artists": "Disclosure, Duke Dumont",
    },
    {
        "id": "synthwave",
        "category": "일렉트로닉",
        "name": "신스웨이브",
        "emoji": "🌆",
        "tags": "신스웨이브,80s,레트로",
        "description": "80년대 네온 레트로 신스웨이브",
        "genre": "Synthwave, Retrowave",
        "mood": "향수적, 네온, 몽환적",
        "tempo_bpm": 110,
        "vocal_style": "남성 보컬, 오토튠",
        "instruments": "아날로그 신스, 드럼 머신, 베이스 신스",
        "production_style": "80s retro, reverb-heavy, cinematic",
        "reference_artists": "The Midnight, Kavinsky",
    },
    {
        "id": "phonk",
        "category": "일렉트로닉",
        "name": "펑크 (Phonk)",
        "emoji": "💀",
        "tags": "펑크,다크,808",
        "description": "다크하고 무거운 펑크 비트",
        "genre": "Phonk, Memphis Rap",
        "mood": "어두운, 공격적, 몽환적",
        "tempo_bpm": 130,
        "vocal_style": "멤피스 랩 샘플, 인스트루멘탈",
        "instruments": "808 베이스, 카우벨, 다크 신스, 샘플",
        "production_style": "distorted 808, cowbell, drift phonk",
        "reference_artists": "Kordhell, DVRST",
    },
    {
        "id": "vaporwave",
        "category": "일렉트로닉",
        "name": "베이퍼웨이브",
        "emoji": "🌸",
        "tags": "베이퍼웨이브,레트로,몽환",
        "description": "90년대 향수의 느린 전자음악",
        "genre": "Vaporwave, Chillwave",
        "mood": "몽환적, 향수적, 초현실적",
        "tempo_bpm": 80,
        "vocal_style": "피치 다운 보컬 샘플, 인스트루멘탈",
        "instruments": "느린 신스, 80s 샘플, 리버브",
        "production_style": "slowed, reverb, mallsoft aesthetic",
        "reference_artists": "Macintosh Plus, Saint Pepsi",
    },
    {
        "id": "edm",
        "category": "일렉트로닉",
        "name": "EDM / 페스티벌",
        "emoji": "🎧",
        "tags": "EDM,페스티벌,클럽",
        "description": "페스티벌·클럽용 빅룸 EDM",
        "genre": "EDM, Big Room House",
        "mood": "에너지틱, 유쾌한, 몰입감",
        "tempo_bpm": 128,
        "vocal_style": "여성 보컬, 코러스",
        "instruments": "신스 리드, 사이드체인 베이스, 킥",
        "production_style": "festival drop, sidechain, euphoric",
        "reference_artists": "Martin Garrix, Avicii",
    },
    {
        "id": "dubstep",
        "category": "일렉트로닉",
        "name": "덥스텝",
        "emoji": "🔊",
        "tags": "덥스텝,베이스,드롭",
        "description": "무거운 베이스 드롭의 덥스텝",
        "genre": "Dubstep, Brostep",
        "mood": "공격적, 강렬한, 다크",
        "tempo_bpm": 140,
        "vocal_style": "보컬 샘플, 인스트루멘탈",
        "instruments": "웍 베이스, 드롭 신스, 서브베이스",
        "production_style": "heavy bass drop, half-time, aggressive",
        "reference_artists": "Skrillex, Virtual Riot",
    },
    {
        "id": "drum_and_bass",
        "category": "일렉트로닉",
        "name": "드럼 앤 베이스",
        "emoji": "🏎️",
        "tags": "DnB,빠른,베이스",
        "description": "빠른 브레이크비트와 헤비 베이스",
        "genre": "Drum and Bass, Jungle",
        "mood": "빠른, 에너지틱, 긴장감",
        "tempo_bpm": 174,
        "vocal_style": "MC 스타일, 인스트루멘탈",
        "instruments": "브레이크비트, 리스 베이스, 패드",
        "production_style": "fast breakbeats, rolling basslines",
        "reference_artists": "Pendulum, Noisia",
    },
    {
        "id": "trance",
        "category": "일렉트로닉",
        "name": "트랜스",
        "emoji": "✨",
        "tags": "트랜스,유포릭,빌드업",
        "description": "유포릭 멜로디의 트랜스",
        "genre": "Trance, Progressive Trance",
        "mood": "유포릭, 몰입, 상승감",
        "tempo_bpm": 138,
        "vocal_style": "에테리얼 여성 보컬",
        "instruments": "슈퍼소 신스, 킥, 플런저 베이스",
        "production_style": "build-up, euphoric breakdown, arpeggios",
        "reference_artists": "Tiësto, Armin van Buuren",
    },
    {
        "id": "ambient",
        "category": "일렉트로닉",
        "name": "앰비언트",
        "emoji": "🌫️",
        "tags": "앰비언트,배경,명상",
        "description": "공간감 있는 몽환적 배경음악",
        "genre": "Ambient, Drone",
        "mood": "몽환적, 평화로운, 신비로운",
        "tempo_bpm": 60,
        "vocal_style": "인스트루멘탈",
        "instruments": "패드 신스, 필드 레코딩, 드론",
        "production_style": "spacious, reverb, slow evolution",
        "reference_artists": "Brian Eno, Hammock",
    },
    # ── 힙합/R&B ──
    {
        "id": "trap",
        "category": "힙합/R&B",
        "name": "트랩",
        "emoji": "🔥",
        "tags": "트랩,힙합,808",
        "description": "808과 하이햇의 현대 트랩",
        "genre": "Trap, Hip-Hop",
        "mood": "어두운, 자신감, 공격적",
        "tempo_bpm": 140,
        "vocal_style": "래핑, 오토튠 보컬",
        "instruments": "808 베이스, 트랩 하이햇, 다크 신스",
        "production_style": "hard 808, rolling hi-hats, dark",
        "reference_artists": "Metro Boomin, Travis Scott",
    },
    {
        "id": "boom_bap",
        "category": "힙합/R&B",
        "name": "붐뱁 힙합",
        "emoji": "📀",
        "tags": "힙합,90s,클래식",
        "description": "90년대 골든에이지 힙합 비트",
        "genre": "Boom Bap, East Coast Hip-Hop",
        "mood": "그루브, 클래식, 거리",
        "tempo_bpm": 95,
        "vocal_style": "래핑, 스크래치",
        "instruments": "샘플 루프, 킥, 스네어, 베이스",
        "production_style": "sample-based, dusty drums, 90s hip-hop",
        "reference_artists": "Nas, Wu-Tang Clan, DJ Premier",
    },
    {
        "id": "neo_soul",
        "category": "힙합/R&B",
        "name": "네오 소울",
        "emoji": "💜",
        "tags": "R&B,소울,그루브",
        "description": "재즈와 힙합이 섞인 네오 소울",
        "genre": "Neo-Soul, R&B",
        "mood": "감성적, 그루브, 따뜻한",
        "tempo_bpm": 88,
        "vocal_style": "소울풀 여성 보컬, 런",
        "instruments": "일렉 피아노, 라이브 드럼, 베이스, 기타",
        "production_style": "organic, live instruments, soulful",
        "reference_artists": "Erykah Badu, D'Angelo, Jill Scott",
    },
    {
        "id": "night_rnb",
        "category": "힙합/R&B",
        "name": "심야 R&B",
        "emoji": "🌙",
        "tags": "R&B,심야,감성",
        "description": "깊은 밤 듣는 감성 R&B",
        "genre": "R&B, Alternative R&B",
        "mood": "감성적, 섹시, 고독한",
        "tempo_bpm": 85,
        "vocal_style": "부드러운 R&B 보컬, 런",
        "instruments": "일렉 피아노, 808, 서브베이스",
        "production_style": "late night, smooth, intimate",
        "reference_artists": "Frank Ocean, SZA, The Weeknd",
    },
    {
        "id": "khiphop",
        "category": "힙합/R&B",
        "name": "한국 힙합",
        "emoji": "🎤",
        "tags": "힙합,한국,랩",
        "description": "한국 힙합·랩 스타일",
        "genre": "Korean Hip-Hop",
        "mood": "자신감, 거리, 진솔한",
        "tempo_bpm": 95,
        "vocal_style": "한국어 랩, 멜로디 랩",
        "instruments": "808, 피아노 샘플, 스트링, 비트",
        "production_style": "K-hiphop, melodic rap, polished",
        "reference_artists": "Jay Park, Zion.T, DEAN",
    },
    # ── 록/메탈 ──
    {
        "id": "rock",
        "category": "록/메탈",
        "name": "락",
        "emoji": "🎸",
        "tags": "락,기타,밴드",
        "description": "기타와 드럼이 살아있는 록",
        "genre": "Rock, Alternative Rock",
        "mood": "강렬한, 자유로운, 에너지틱",
        "tempo_bpm": 130,
        "vocal_style": "남성 보컬, 파워풀",
        "instruments": "일렉 기타, 베이스, 드럼, 오버드라이브",
        "production_style": "raw, distorted guitars, live band",
        "reference_artists": "Foo Fighters, Arctic Monkeys",
    },
    {
        "id": "metal",
        "category": "록/메탈",
        "name": "메탈",
        "emoji": "🤘",
        "tags": "메탈,헤비,기타",
        "description": "헤비하고 공격적인 메탈",
        "genre": "Heavy Metal, Metalcore",
        "mood": "공격적, 강렬한, 다크",
        "tempo_bpm": 150,
        "vocal_style": "스크리밍, 그로울, 파워 보컬",
        "instruments": "다운튜닝 기타, 더블 킥, 베이스",
        "production_style": "heavy distortion, double kick, aggressive",
        "reference_artists": "Metallica, Bring Me The Horizon",
    },
    {
        "id": "punk",
        "category": "록/메탈",
        "name": "펑크 록",
        "emoji": "⚡",
        "tags": "펑크,빠른,에너지",
        "description": "빠르고 거친 펑크 록",
        "genre": "Punk Rock, Pop Punk",
        "mood": "반항적, 에너지틱, 짧고 강렬",
        "tempo_bpm": 170,
        "vocal_style": "거친 보컬, 코러스",
        "instruments": "파워 코드 기타, 베이스, 빠른 드럼",
        "production_style": "raw, fast, garage punk",
        "reference_artists": "Green Day, The Offspring",
    },
    {
        "id": "shoegaze",
        "category": "록/메탈",
        "name": "슈게이즈",
        "emoji": "🌊",
        "tags": "슈게이즈,몽환,기타",
        "description": "리버브 기타 벽의 몽환적 사운드",
        "genre": "Shoegaze, Dream Pop",
        "mood": "몽환적, 압도적, 감성적",
        "tempo_bpm": 100,
        "vocal_style": "몽롱한 보컬, 믹스 뒤",
        "instruments": "리버브 기타, 드럼, 베이스, 패드",
        "production_style": "wall of sound, heavy reverb, ethereal",
        "reference_artists": "My Bloody Valentine, Slowdive",
    },
    {
        "id": "post_rock",
        "category": "록/메탈",
        "name": "포스트 록",
        "emoji": "🏔️",
        "tags": "포스트록,빌드업,시네마틱",
        "description": "서서히 쌓아 올리는 시네마틱 포스트 록",
        "genre": "Post-Rock, Instrumental Rock",
        "mood": "서사적, 웅장한, 감동적",
        "tempo_bpm": 90,
        "vocal_style": "인스트루멘탈",
        "instruments": "클린/디스토션 기타, 드럼, 베이스, 스트링",
        "production_style": "crescendo build-up, cinematic, epic",
        "reference_artists": "Explosions in the Sky, Godspeed You! Black Emperor",
    },
    {
        "id": "heavy_drums",
        "category": "록/메탈",
        "name": "드럼 강조",
        "emoji": "🥁",
        "tags": "드럼,비트,그루브",
        "description": "드럼과 퍼커션이 전면에 나오는 음악",
        "genre": "Rock, Funk, Hip-Hop",
        "mood": "그루브, 파워풀, 리드미컬",
        "tempo_bpm": 100,
        "vocal_style": "인스트루멘탈, 래핑",
        "instruments": "킥, 스네어, 하이햇, 톰, 퍼커션",
        "production_style": "drum-forward mix, punchy transients",
        "reference_artists": "John Bonham, Questlove",
    },
    # ── 팝/시티팝 ──
    {
        "id": "kpop",
        "category": "팝",
        "name": "K-Pop",
        "emoji": "🇰🇷",
        "tags": "K-Pop,대중,세련",
        "description": "밝고 세련된 한국 팝",
        "genre": "K-Pop",
        "mood": "밝은, 에너지틱, 세련된",
        "tempo_bpm": 120,
        "vocal_style": "여성/남성 보컬, 듀엣",
        "instruments": "신스, 일렉 기타, 808, 드럼 머신",
        "production_style": "polished, wide stereo, punchy",
        "reference_artists": "NewJeans, IU, BTS",
    },
    {
        "id": "city_pop",
        "category": "팝",
        "name": "시티팝",
        "emoji": "🌃",
        "tags": "시티팝,80s,일본",
        "description": "80년대 일본 시티팝 감성",
        "genre": "City Pop, AOR",
        "mood": "세련된, 향수적, 도시적",
        "tempo_bpm": 105,
        "vocal_style": "부드러운 일본어/한국어 보컬",
        "instruments": "신스, 일렉 피아노, 베이스, 세션",
        "production_style": "80s Japanese, glossy, urban night",
        "reference_artists": "Tatsuro Yamashita, Mariya Takeuchi",
    },
    {
        "id": "indie_pop",
        "category": "팝",
        "name": "인디 팝",
        "emoji": "🌸",
        "tags": "인디,팝,감성",
        "description": "감성적인 인디 팝",
        "genre": "Indie Pop, Bedroom Pop",
        "mood": "감성적, 따뜻한, 로파이",
        "tempo_bpm": 110,
        "vocal_style": "부드러운 보컬, 듀엣",
        "instruments": "기타, 신스, 드럼 머신, 베이스",
        "production_style": "bedroom pop, DIY, intimate",
        "reference_artists": "Clairo, Cigarettes After Sex",
    },
    {
        "id": "dance_pop",
        "category": "팝",
        "name": "댄스 팝",
        "emoji": "💃",
        "tags": "댄스,팝,신나는",
        "description": "춤추고 싶어지는 댄스 팝",
        "genre": "Dance Pop, Electropop",
        "mood": "신나는, 밝은, 에너지틱",
        "tempo_bpm": 125,
        "vocal_style": "여성 보컬, 코러스",
        "instruments": "신스, 킥, 클랩, 베이스",
        "production_style": "catchy hook, danceable, polished pop",
        "reference_artists": "Dua Lipa, Lady Gaga",
    },
    {
        "id": "ballad",
        "category": "팝",
        "name": "발라드",
        "emoji": "💔",
        "tags": "발라드,감성,피아노",
        "description": "감성적인 한국식 발라드",
        "genre": "Ballad, K-Ballad",
        "mood": "감성적, 로맨틱, 서정적",
        "tempo_bpm": 72,
        "vocal_style": "감성적 보컬, 파워 보컬",
        "instruments": "피아노, 스트링, 어쿠스틱 기타",
        "production_style": "emotional, building climax, orchestral",
        "reference_artists": "Taeyeon, Paul Kim",
    },
    {
        "id": "piano",
        "category": "팝",
        "name": "피아노 반주",
        "emoji": "🎹",
        "tags": "피아노,발라드,감성",
        "description": "피아노 중심의 감성 반주",
        "genre": "Piano Pop, Ballad",
        "mood": "감성적, 서정적, 잔잔한",
        "tempo_bpm": 72,
        "vocal_style": "감성적 보컬",
        "instruments": "그랜드 피아노, 스트링, 가벼운 드럼",
        "production_style": "piano-led, minimal, emotional",
        "reference_artists": "Yiruma, Adele",
    },
    # ── 시네마틱/OST ──
    {
        "id": "cinematic",
        "category": "시네마틱/OST",
        "name": "시네마틱 오케스트라",
        "emoji": "🎬",
        "tags": "시네마틱,웅장,영화",
        "description": "영화 같은 웅장한 오케스트라",
        "genre": "Cinematic, Orchestral",
        "mood": "웅장한, 드라마틱, 감동적",
        "tempo_bpm": 90,
        "vocal_style": "코러스, 인스트루멘탈",
        "instruments": "오케스트라, 스트링, 브라스, 타악기",
        "production_style": "epic, Hans Zimmer style, trailer music",
        "reference_artists": "Hans Zimmer, Two Steps From Hell",
    },
    {
        "id": "anime_ost",
        "category": "시네마틱/OST",
        "name": "애니 OST",
        "emoji": "🎌",
        "tags": "애니,OST,일본",
        "description": "애니메이션 사운드트랙 스타일",
        "genre": "Anime OST, J-Rock, Orchestral Pop",
        "mood": "감동적, 희망적, 드라마틱",
        "tempo_bpm": 130,
        "vocal_style": "일본어 보컬, 코러스",
        "instruments": "록 밴드, 오케스트라, 신스",
        "production_style": "anime opening/ending, emotional build",
        "reference_artists": "Yoko Kanno, LiSA, RADWIMPS",
    },
    {
        "id": "game_ost",
        "category": "시네마틱/OST",
        "name": "게임 OST",
        "emoji": "🎮",
        "tags": "게임,OST,어드벤처",
        "description": "RPG·어드벤처 게임 BGM 스타일",
        "genre": "Video Game Music, Chiptune",
        "mood": "모험적, 향수적, 몰입",
        "tempo_bpm": 100,
        "vocal_style": "인스트루멘탈, 가끔 보컬",
        "instruments": "오케스트라, 신스, 칩튠 요소",
        "production_style": "adventure theme, loopable, nostalgic",
        "reference_artists": "Nobuo Uematsu, C418",
    },
    {
        "id": "horror",
        "category": "시네마틱/OST",
        "name": "호러 사운드트랙",
        "emoji": "👻",
        "tags": "호러,다크,긴장",
        "description": "공포 영화 같은 긴장감 있는 음악",
        "genre": "Dark Ambient, Horror Score",
        "mood": "불안한, 어두운, 긴장감",
        "tempo_bpm": 65,
        "vocal_style": "인스트루멘탈, 이펙트",
        "instruments": "드론, 디스토션, 스트링, 효과음",
        "production_style": "unsettling, dissonant, jump scare build",
        "reference_artists": "Akira Yamaoka, Trent Reznor",
    },
    {
        "id": "dark_academia",
        "category": "시네마틱/OST",
        "name": "다크 아카데미아",
        "emoji": "📜",
        "tags": "다크아카데미아,클래식,고딕",
        "description": "고딕하고 클래식한 다크 아카데미아",
        "genre": "Classical, Dark Ambient, Neoclassical",
        "mood": "고딕, 지적인, 신비로운",
        "tempo_bpm": 75,
        "vocal_style": "인스트루멘탈, 라틴 코러스",
        "instruments": "피아노, 바이올린, 첼로, 오르간",
        "production_style": "gothic, library aesthetic, candlelight",
        "reference_artists": "Max Richter, Ólafur Arnalds",
    },
    # ── 월드/포크 ──
    {
        "id": "latin",
        "category": "월드/포크",
        "name": "라틴 / 레게톤",
        "emoji": "💃",
        "tags": "라틴,레게톤,댄스",
        "description": "열정적인 라틴 리듬",
        "genre": "Reggaeton, Latin Pop",
        "mood": "열정적, 댄스, 여름",
        "tempo_bpm": 95,
        "vocal_style": "스페인어 보컬, 랩",
        "instruments": "데무로 비트, 퍼커션, 베이스, 트럼펫",
        "production_style": "dembow rhythm, tropical, party",
        "reference_artists": "Bad Bunny, Shakira",
    },
    {
        "id": "afrobeat",
        "category": "월드/포크",
        "name": "아프로비트",
        "emoji": "🌍",
        "tags": "아프로,그루브,댄스",
        "description": "아프리카 리듬의 그루비한 비트",
        "genre": "Afrobeat, Afropop",
        "mood": "그루브, 축제, 에너지틱",
        "tempo_bpm": 115,
        "vocal_style": "영어/현지어 보컬, 코러스",
        "instruments": "퍼커션, 베이스, 기타, 브라스",
        "production_style": "polyrhythmic, danceable, warm",
        "reference_artists": "Burna Boy, Wizkid, Fela Kuti",
    },
    {
        "id": "folk",
        "category": "월드/포크",
        "name": "포크 / 어쿠스틱",
        "emoji": "🪕",
        "tags": "포크,어쿠스틱,자연",
        "description": "어쿠스틱 기타 중심의 포크",
        "genre": "Folk, Acoustic",
        "mood": "자연스러운, 따뜻한, 서정적",
        "tempo_bpm": 100,
        "vocal_style": "스토리텔링 보컬",
        "instruments": "어쿠스틱 기타, 밴조, 하모니카",
        "production_style": "organic, storytelling, campfire",
        "reference_artists": "Bob Dylan, Fleet Foxes",
    },
    {
        "id": "country",
        "category": "월드/포크",
        "name": "컨트리",
        "emoji": "🤠",
        "tags": "컨트리,어쿠스틱,미국",
        "description": "미국 컨트리 뮤직",
        "genre": "Country, Americana",
        "mood": "향수적, 따뜻한, 이야기",
        "tempo_bpm": 105,
        "vocal_style": "남성/여성 컨트리 보컬",
        "instruments": "어쿠스틱 기타, 스틸 기타, 바이올린, 베이스",
        "production_style": "twang, Nashville sound, storytelling",
        "reference_artists": "Johnny Cash, Taylor Swift (country era)",
    },
    {
        "id": "blues",
        "category": "월드/포크",
        "name": "블루스",
        "emoji": "🎵",
        "tags": "블루스,기타,슬픈",
        "description": "슬픔과 그루브의 블루스",
        "genre": "Blues, Blues Rock",
        "mood": "슬픈, 그루브, 진솔한",
        "tempo_bpm": 80,
        "vocal_style": "블루스 보컬, 허스키",
        "instruments": "일렉 기타, 하모니카, 베이스, 드럼",
        "production_style": "12-bar blues, guitar bends, raw",
        "reference_artists": "B.B. King, Stevie Ray Vaughan",
    },
    # ── 무드/상황 ──
    {
        "id": "sunny",
        "category": "무드/상황",
        "name": "맑은 날 / 드라이브",
        "emoji": "☀️",
        "tags": "맑음,드라이브,밝음",
        "description": "화창한 날 드라이브 음악",
        "genre": "Indie Pop, Surf Rock",
        "mood": "밝은, 자유로운, 상쾌한",
        "tempo_bpm": 115,
        "vocal_style": "밝은 보컬",
        "instruments": "클린 기타, 베이스, 라이트 드럼",
        "production_style": "bright, open, feel-good",
        "reference_artists": "Phoenix, Wallows",
    },
    {
        "id": "workout",
        "category": "무드/상황",
        "name": "운동 / 워크아웃",
        "emoji": "💪",
        "tags": "운동,에너지,동기부여",
        "description": "운동할 때 듣는 고에너지 음악",
        "genre": "Hip-Hop, EDM, Rock",
        "mood": "에너지틱, 동기부여, 강렬",
        "tempo_bpm": 140,
        "vocal_style": "래핑, 파워풀 보컬",
        "instruments": "808, 기타, 킥, 신스",
        "production_style": "high energy, motivational, pump up",
        "reference_artists": "Eminem, Survivor",
    },
    {
        "id": "meditation",
        "category": "무드/상황",
        "name": "명상 / 힐링",
        "emoji": "🧘",
        "tags": "명상,힐링,평화",
        "description": "명상과 힐링을 위한 음악",
        "genre": "New Age, Meditation",
        "mood": "평화로운, 고요한, 영적",
        "tempo_bpm": 50,
        "vocal_style": "인스트루멘탈, 만트라",
        "instruments": "싱잉볼, 플루트, 패드, 자연 소리",
        "production_style": "healing frequencies, binaural, spa",
        "reference_artists": "Deuter, Steven Halpern",
    },
    {
        "id": "christmas",
        "category": "무드/상황",
        "name": "크리스마스 / 겨울",
        "emoji": "🎄",
        "tags": "크리스마스,겨울,따뜻",
        "description": "겨울·크리스마스 분위기 음악",
        "genre": "Christmas, Winter Pop",
        "mood": "따뜻한, 행복한, 축제",
        "tempo_bpm": 100,
        "vocal_style": "코러스, 캐롤 보컬",
        "instruments": "벨, 피아노, 스트링, 오르간",
        "production_style": "festive, jingle bells, cozy winter",
        "reference_artists": "Mariah Carey, Michael Bublé",
    },
    {
        "id": "funk",
        "category": "무드/상황",
        "name": "펑크",
        "emoji": "🕺",
        "tags": "펑크,그루브,댄스",
        "description": "그루브 넘치는 펑크",
        "genre": "Funk, Disco",
        "mood": "그루브, 유쾌한, 댄스",
        "tempo_bpm": 110,
        "vocal_style": "소울 보컬, 코러스",
        "instruments": "베이스(슬랩), 기타, 브라스, 드럼",
        "production_style": "slap bass, tight groove, 70s funk",
        "reference_artists": "James Brown, Daft Punk",
    },
    {
        "id": "disco",
        "category": "무드/상황",
        "name": "디스코",
        "emoji": "🪩",
        "tags": "디스코,70s,댄스",
        "description": "70년대 디스코 플로어",
        "genre": "Disco, Nu-Disco",
        "mood": "유쾌한, 댄스, 화려한",
        "tempo_bpm": 120,
        "vocal_style": "소울풀 보컬, 코러스",
        "instruments": "스트링, 베이스, 하이햇, 브라스",
        "production_style": "four-on-the-floor, string hits, groovy",
        "reference_artists": "Bee Gees, Chic, Donna Summer",
    },
]

PRESET_FIELDS = (
    "name", "description", "genre", "mood", "tempo_bpm", "key_signature",
    "vocal_style", "instruments", "production_style", "reference_artists",
    "extra_notes", "tags", "emoji",
)


def list_presets() -> list[dict]:
    return GENRE_PRESETS


def list_categories() -> list[str]:
    seen = []
    for p in GENRE_PRESETS:
        cat = p.get("category", "기타")
        if cat not in seen:
            seen.append(cat)
    return seen


def list_presets_by_category(category: str | None = None) -> list[dict]:
    if not category:
        return GENRE_PRESETS
    return [p for p in GENRE_PRESETS if p.get("category") == category]


def get_preset(preset_id: str) -> dict | None:
    return next((p for p in GENRE_PRESETS if p["id"] == preset_id), None)


def preset_to_profile_data(preset: dict) -> dict:
    return {f: preset.get(f) for f in PRESET_FIELDS if preset.get(f) is not None}
