#!/usr/bin/env python3
"""Generate curtin config from disk_plan.json — preserves whick-music partition."""
from __future__ import annotations

import json
import sys
from pathlib import Path

# Minimal curtin schema — expanded when Ubuntu UAB live ships
TEMPLATE = """# generated by generate-curtin-config.py — do not edit
early_commands:
  map:
    detect_disk: |
      # Whick: music partition preserved per disk_plan.json
      echo "Whick curtin install"

partitioning:
  config:
    - {name: disk0, type: disk, ptable: gpt, match: {size: largest, ssd: true}}
{efi_part}
{root_part}
{music_part}

sources:
  ubuntu:
    uri: http://archive.ubuntu.com/ubuntu/
    suite: resolute
    components: [main, restricted]
    arch: amd64

late_commands:
  map:
    mount_music: |
      mkdir -p /target{music_mount}
      grep -q '{music_mount}' /target/etc/fstab || echo 'LABEL={music_label} {music_mount} ext4 defaults 0 2' >> /target/etc/fstab
"""


def main() -> None:
    plan_path = Path(sys.argv[1] if len(sys.argv) > 1 else "disk_plan.json")
    plan = json.loads(plan_path.read_text())
    music_mount = "/mnt/music"
    music_label = "whick-music"
    preserve = plan.get("preserve") or []
    if preserve:
        music_mount = preserve[0].get("mount") or music_mount
        music_label = preserve[0].get("label") or music_label

    efi_part = ""
    if plan.get("uefi"):
        efi_part = (
            "    - {name: efi0, type: partition, size: 512M, device: disk0, "
            "flag: boot, wipe: superblock, number: 1, fstype: fat32, mount: /boot/efi}\n"
        )

    root_gb = plan.get("install_reserve_gb") or 32
    root_part = (
        f"    - {{name: root0, type: partition, size: {root_gb}G, device: disk0, "
        f"wipe: superblock, number: 2, fstype: ext4, mount: /, label: whick-root}}\n"
    )

    music_part = ""
    create = plan.get("create") or []
    music_create = next((c for c in create if c.get("role") == "music"), None)
    if music_create and plan.get("mode") == "fresh":
        music_part = (
            f"    - {{name: music0, type: partition, size: -1, device: disk0, "
            f"wipe: superblock, number: 3, fstype: ext4, mount: {music_mount}, "
            f"label: {music_label}}}\n"
        )
    elif preserve:
        music_part = f"    # preserve existing {preserve[0].get('path')} — not in curtin wipe\n"

    print(
        TEMPLATE.format(
            efi_part=efi_part,
            root_part=root_part,
            music_part=music_part,
            music_mount=music_mount,
            music_label=music_label,
        )
    )


if __name__ == "__main__":
    main()
